spring.application.name=vehiculos-app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://vehiculos_app_db_user:UlMvV1rXauonnncasK9DRRUEboExiTPV@dpg-d8ghvl6q1p3s739k46j0-a/vehiculos_app_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never

server.port=${PORT:8080}