spring.application.name=vehiculos-app

# ==========================================
# MOCK DATA
# ==========================================

# No se utiliza PostgreSQL.
# Los vehículos se cargan desde:
# src/main/resources/mock/vehiculos.json

# ==========================================
# SERVER
# ==========================================

server.port=${PORT:3000}